package com.diximonline.cbspaymentsimulator.acxf.interfaces;

import java.math.BigDecimal;

import com.diximonline.cbspaymentsimulator.acxf.types.ObjAchOtrfUserArray;
import com.diximonline.cbspaymentsimulator.acxf.types.ObjectFactory;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-09-14T15:50:37.253+07:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://com/icsfs/banks/ws/BanksMiddleware_PE07COT00.wsdl", name = "BanksMiddleware_PE07COT00")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BanksMiddlewarePE07COT00 {

    @WebMethod(operationName = "e07cot01", action = "http://com/icsfs/banks/ws/BanksMiddleware_PE07COT00.wsdl/e07cot01")
    public void e07Cot01(

        @WebParam(partName = "iTraType", name = "iTraType")
        BigDecimal iTraType,
        @WebParam(partName = "iSysSourceCode", name = "iSysSourceCode")
        BigDecimal iSysSourceCode,
        @WebParam(partName = "iSouCode", name = "iSouCode")
        BigDecimal iSouCode,
        @WebParam(partName = "iTraDate", name = "iTraDate")
        String iTraDate,
        @WebParam(partName = "reqLanInd_inout", mode = WebParam.Mode.INOUT, name = "reqLanInd_inout")
        Holder<BigDecimal> reqLanIndInout,
        @WebParam(partName = "inpChannelId_inout", mode = WebParam.Mode.INOUT, name = "inpChannelId_inout")
        Holder<BigDecimal> inpChannelIdInout,
        @WebParam(partName = "inpChannelRefNum_inout", mode = WebParam.Mode.INOUT, name = "inpChannelRefNum_inout")
        Holder<String> inpChannelRefNumInout,
        @WebParam(partName = "allAchTra_out", mode = WebParam.Mode.INOUT, name = "allAchTra_out")
        Holder<ObjAchOtrfUserArray> allAchTraOut,
        @WebParam(partName = "outReqId_out", mode = WebParam.Mode.INOUT, name = "outReqId_out")
        Holder<String> outReqIdOut,
        @WebParam(partName = "outStatus_out", mode = WebParam.Mode.INOUT, name = "outStatus_out")
        Holder<BigDecimal> outStatusOut,
        @WebParam(partName = "outMsgTxt_out", mode = WebParam.Mode.INOUT, name = "outMsgTxt_out")
        Holder<String> outMsgTxtOut,
        @WebParam(partName = "outProcData_out", mode = WebParam.Mode.INOUT, name = "outProcData_out")
        Holder<String> outProcDataOut,
        @WebParam(partName = "outDetInfo_out", mode = WebParam.Mode.INOUT, name = "outDetInfo_out")
        Holder<String> outDetInfoOut,
        @WebParam(partName = "dbAppErr_out", mode = WebParam.Mode.INOUT, name = "dbAppErr_out")
        Holder<BigDecimal> dbAppErrOut
    );

    @WebMethod(operationName = "e07cot02", action = "http://com/icsfs/banks/ws/BanksMiddleware_PE07COT00.wsdl/e07cot02")
    public void e07Cot02(

        @WebParam(partName = "iBraCode", name = "iBraCode")
        BigDecimal iBraCode,
        @WebParam(partName = "iRefType", name = "iRefType")
        BigDecimal iRefType,
        @WebParam(partName = "iRefYear", name = "iRefYear")
        BigDecimal iRefYear,
        @WebParam(partName = "iRefNum", name = "iRefNum")
        BigDecimal iRefNum,
        @WebParam(partName = "iSouCode", name = "iSouCode")
        BigDecimal iSouCode,
        @WebParam(partName = "reqLanInd_inout", mode = WebParam.Mode.INOUT, name = "reqLanInd_inout")
        Holder<BigDecimal> reqLanIndInout,
        @WebParam(partName = "inpChannelId_inout", mode = WebParam.Mode.INOUT, name = "inpChannelId_inout")
        Holder<BigDecimal> inpChannelIdInout,
        @WebParam(partName = "inpChannelRefNum_inout", mode = WebParam.Mode.INOUT, name = "inpChannelRefNum_inout")
        Holder<String> inpChannelRefNumInout,
        @WebParam(partName = "outReqId_out", mode = WebParam.Mode.INOUT, name = "outReqId_out")
        Holder<String> outReqIdOut,
        @WebParam(partName = "outStatus_out", mode = WebParam.Mode.INOUT, name = "outStatus_out")
        Holder<BigDecimal> outStatusOut,
        @WebParam(partName = "outMsgTxt_out", mode = WebParam.Mode.INOUT, name = "outMsgTxt_out")
        Holder<String> outMsgTxtOut,
        @WebParam(partName = "outProcData_out", mode = WebParam.Mode.INOUT, name = "outProcData_out")
        Holder<String> outProcDataOut,
        @WebParam(partName = "outDetInfo_out", mode = WebParam.Mode.INOUT, name = "outDetInfo_out")
        Holder<String> outDetInfoOut,
        @WebParam(partName = "dbAppErr_out", mode = WebParam.Mode.INOUT, name = "dbAppErr_out")
        Holder<BigDecimal> dbAppErrOut
    );
}
